name: HOMOL
on:
  push:
    branches:
      - release
jobs:  
  
  CD:
   runs-on: ubuntu-latest
   environment: PRD
   
   steps:
      - name: Configure SSH Azure Cloud
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/azure-cloud.key
          chmod 600 ~/.ssh/azure-cloud.key
          cat >>~/.ssh/config <<END
          Host azure-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/azure-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.DES_SSH_USER }}
          SSH_KEY: ${{ secrets.DES_SSH_KEY }}
          SSH_HOST: ${{ secrets.DES_SSH_HOST }}     

     
     
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribuition: 'corretto'
          cache: maven

      - name: Run the tests
        run: mvn -B -f pom.xml test jacoco:prepare-agent jacoco:report

  
      #- name: SonarCloud Analyse
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
        #run: |
          #mvn -B verify sonar:sonar 
          #-Dsonar.host.url=http://sonarcloud.io 
          #-Dsonar.organization=lindemberg-chagas-1
          #-Dsonar.projectKey=Lindemberg-Chagas_java-api-Hackaton
          #-Dsonar.language=java
          #-Dsonar.java.coveragePlugin=jacoco
          #-Dmaven.test.skip=true
          
      - name: Build the application
        run: mvn -B -f pom.xml clean install -Dmaven.test.skip=true

      - name: Deploy the application
        run: |
          ssh azure-cloud 'sudo systemctl stop prd-react'
          ssh azure-cloud 'sudo rm -rf /app/prd-react'
          scp -r target/java-api.jar google-cloud:/home/desafio/prd-react
          ssh azure-cloud 'sudo mv /home/desafio/prd-react /app/prd-react'
          ssh azure-cloud 'sudo systemctl start prd-react'
